version: '3'
services:
  gitlab-runner:
    image: 'gitlab/gitlab-runner:alpine'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/gitlab-runnerw
    restart: unless-stopped